### ISSUE TITLE
[idea] can we make hamilton run in a distributed manner?

### ISSUE THREAD

**Issue by skrawcz** [stitchfix/hamilton#10]
# What's the idea?

Hamilton runs locally on data that fits in memory on a single core.

Can we improve speed and data scale by making hamilton run in a parallel and distributed manner?

# Why we think it should be possible?
Hamilton ultimately creates a DAG before executing. The idea would be to distribute various parts of this DAG.

We'd have to figure out initial data loading, but other than that, it seems like we're solving something that other systems have already solved for us. Can we harness them? Perhaps by going from a Hamilton DAG and "compiling" it to the target system of choice?

# Ideas to explore

- [x] [ray](https://github.com/ray-project/ray)
- [x] [spark](http://spark.apache.org/docs/latest/)
- [x] [dask](https://dask.org/)
- [ ] your idea here!

**Comment by skrawcz** [comment]
@chmp ❤️  the thinking. 

>As the column types are not checked anymore, you can probably also replace pandas with dask.dataframe and work with distributed series / dataframe objects directly. This way you can distribute computation also along the rows. 

Will have to think about the implications of this; ideally the the functions one writes in Hamilton can be stable/not leak too much of the underlying execution context.

**Comment by elijahbenizzy** [comment]
@chmp took your thinking and expanded it out! Would love thoughts/feedback -- I think this allows what you have above nicely, but also enables us to expand to a variety of other backends in a clean, extensible way: https://docs.google.com/document/d/17LjBzv2hvSs8BSbjeKasWjY6UAMKxrE1En5bjkkFhto/edit?usp=sharing

**Comment by skrawcz** [comment]
From a process perspective, I think if we started a branch called `distributed_prototype` (which I have) to merge this type of work into, then I think we can be a bit looser in PRs until we have a better feel for things.

**Comment by skrawcz** [comment]
@chmp if you have time, mind checking out the `distributed_prototype` branch -- I refactored things, and add Ray, and Koalas on Spark 3.2, and the ability to not have to return a pandas dataframe.

**Comment by skrawcz** [comment]
Ray workflows seems like something we could easily add too https://docs.ray.io/en/latest/workflows/concepts.html

**Comment by skrawcz** [comment]
Closed because we have experimental versions of this merged!
