### ISSUE TITLE
Move away from using setup.py for packaging hamilton

### ISSUE THREAD

**Issue by skrawcz** [stitchfix/hamilton#12]
# what?
Python is moving away from setup.py and to setup.cfg and pyproject.toml.
See https://packaging.python.org/tutorials/packaging-projects/.

# impact of not doing this
Maintenance burden/becomes harder to maintain.

# impact of doing this change
We're ready for future python changes more easily -- and can build a more complex package if necessary(?).

**Comment by skrawcz** [comment]
> Hi ! can I work on this issue?

Sure, yes please. Feel free to submit a Pull Request when you have something for us to review.

**Comment by elijahbenizzy** [comment]
We are moving repositories! Please see the new version of this issue at https://github.com/DAGWorks-Inc/hamilton/issues/10. Also, please give us a star/update any of your internal links.
