### ISSUE TITLE
Expose tags and function metadata to decorators

### ISSUE THREAD

**Issue by skrawcz** [stitchfix/hamilton#138]
**Is your feature request related to a problem? Please describe.**
With tagging, we can annotate functions with metadata. It would be useful to allow decorators access to this, and other metadata accumulated. 

E.g. tags could be used as a means to help inform what should happen if a `check_output` decorator runs a test and it fails. That is, if we standardize on tag keys, then decorators could assume them and make use of them.

**Describe the solution you'd like**
Enable decorators access to a `context` or some variable that would allow them to get at this information. 

**Describe alternatives you've considered**
N/A

**Additional context**
Taken from the discussion with whylabs folks on what would be useful.

**Comment by elijahbenizzy** [comment]
Seems like a pretty reasonable thing to expose, and probably not too tricky, but I haven't scoped it out. Whylabs could be a great use-case, I'll try to think of others. Will likely not implement till we have a motivating example though.

**Comment by elijahbenizzy** [comment]
We are moving repositories! Please see the new version of this issue at https://github.com/DAGWorks-Inc/hamilton/issues/31. Also, please give us a star/update any of your internal links.
