### ISSUE TITLE
[prototype] NVMTabular support

### ISSUE THREAD

**Issue by skrawcz** [stitchfix/hamilton#150]
**Is your feature request related to a problem? Please describe.**
NVMTabular is a way to write ETL feature code for nvidia GPUs. Is there a Hamilton way to help organize the workflow required to run NVMTabular?

**Describe the solution you'd like**
The goal of the prototype is to figure out how Hamilton could be best used.

**Describe alternatives you've considered**
N/A

**Additional context**
E.g. what would the Hamilton version of https://github.com/NVIDIA-Merlin/NVTabular/blob/main/examples/getting-started-movielens/02-ETL-with-NVTabular.ipynb be?

**Comment by elijahbenizzy** [comment]
We are moving repositories! Please see the new version of this issue at https://github.com/DAGWorks-Inc/hamilton/issues/34. Also, please give us a star/update any of your internal links.

Note that everything else (slack community, pypi packages, etc...) will not change at all.
