### ISSUE TITLE
Add documentation showing %%writefile in a notebook

### ISSUE THREAD

**Issue by skrawcz** [stitchfix/hamilton#153]
This is another way someone could develop hamilton in a notebook -
https://ipython.readthedocs.io/en/stable/interactive/magics.html#cellmagic-writefile

We should add some documentation/example around this.

**Comment by elijahbenizzy** [comment]
We are moving repositories! Please see the new version of this issue at https://github.com/DAGWorks-Inc/hamilton/issues/35. Also, please give us a star/update any of your internal links.

Note that everything else (slack community, pypi packages, etc...) will not change at all.
