### ISSUE TITLE
[example] using Hamilton with duckdb 

### ISSUE THREAD

**Issue by skrawcz** [stitchfix/hamilton#158]
# idea
https://duckdb.org/ is a hot new tool. It could be a nice way to load data for people. We should show some ways people could use it with Hamilton. IIRC duckdb does predicate push down when querying files like parquet, which can be faster than loading them via pandas and then doing some filters.

Rough sketch:

1. data_loaders module that connects with duckdb
2. feature_logic module(s) that works from the output of the data_loaders

**Comment by shrey231** [comment]
Could I be assigned this issue?

**Comment by elijahbenizzy** [comment]
@shrey231 sorry I didn't see this!! I would love some thoughts -- I've built out some basic SQL adapters, but I'd love to see more + transforms 🙏

**Comment by skrawcz** [comment]
@shrey231 if you're still interested, let me know and we can assign it to you.

**Comment by skrawcz** [comment]
#195 did this.
