### ISSUE TITLE
Configurable data quality checks

### ISSUE THREAD

**Issue by skrawcz** [stitchfix/hamilton#164]
**Is your feature request related to a problem? Please describe.**
We should be able to configure whether we want data quality to run or not at DAG build/run time.

**Describe the solution you'd like**
Allowing for fine-grained control over the behavior of specific checks. This will enable the user to turn on and off certain checks at runtime.

i.e. some configuration that a user can adjust/modify via JSON or YAML or both...

**Describe alternatives you've considered**
N/A

**Additional context**
https://github.com/stitchfix/hamilton/pull/149 prototypes some approaches here.

**Comment by elijahbenizzy** [comment]
We are moving repositories! Please see the new version of this issue at https://github.com/DAGWorks-Inc/hamilton/issues/39. Also, please give us a star/update any of your internal links.

Note that everything else (slack community, pypi packages, etc...) will not change at all.
