### ISSUE TITLE
Ability to data profile node outputs for creating data quality checks

### ISSUE THREAD

**Issue by skrawcz** [stitchfix/hamilton#165]
**Is your feature request related to a problem? Please describe.**
Data profiling is a way to help bootstrap creating data quality checks. 
Data profiling is also a way to facilitate data exploration, by providing summary statistics over data.

**Describe the solution you'd like**
A user should be able to profile their DAG, or a set of nodes, and get out some summary statistics.
Those statistics could then be used to bootstrap data quality, i.e. check_output(), decorators, but the output should be standalone.

**Describe alternatives you've considered**
Haven't considered many options. But there are a few libraries that do data profiling already.

**Additional context**
Systems like whylogs, great expectations, use profiling to help with the user experience.
Standalone libraries like https://github.com/capitalone/DataProfiler also exist.

https://github.com/stitchfix/hamilton/pull/149 does a little to prototype in this area too.

**Comment by elijahbenizzy** [comment]
We are moving repositories! Please see the new version of this issue at https://github.com/DAGWorks-Inc/hamilton/issues/40. Also, please give us a star/update any of your internal links.

Note that everything else (slack community, pypi packages, etc...) will not change at all.
