### ISSUE TITLE
Help bootstrap `check_output()` decorator.

### ISSUE THREAD

**Issue by skrawcz** [stitchfix/hamilton#166]
**Is your feature request related to a problem? Please describe.**
Can we help users bootstrap the `check_output()` decorator?

**Describe the solution you'd like**
Setting up data quality is possible to do manually, but with some knowledge of the data, could be automated, or at least partially automated.

Idea: 

1. give a data profile, can we generate the `check_output()` decorator to add?
2. could we also automatically update the code with it, rather than having the user cut and paste it?

**Describe alternatives you've considered**
Not doing this. But I think having a way to speed up adding it to a code base is a good idea.

**Additional context**
Related to #164 and #165.

**Comment by elijahbenizzy** [comment]
We are moving repositories! Please see the new version of this issue at https://github.com/DAGWorks-Inc/hamilton/issues/41. Also, please give us a star/update any of your internal links.

Note that everything else (slack community, pypi packages, etc...) will not change at all.
