### ISSUE TITLE
Scaling to 100K+ Nodes 

### ISSUE THREAD

**Issue by skrawcz** [stitchfix/hamilton#168]
# Current behavior
Creating a DAG with 100K+ nodes is slow. It took 1117.1986498832703 seconds for it to complete for the first example below.
Execution time was then 450 seconds for 100K colums at 10 rows deep running a validation check on them.

I then tried to do the same thing with Ray -- and it took longer, which makes sense since we're delegating over to Ray 100K+ tasks.
Interestingly Ray did not speed things up -- guess there's too much overhead here somewhere for the size of the task...

We should probably have a better way of handling creation of super large DAGs.

Use case: biology -- I came across this example in the Pandera discord channel where a user was trying to use pandera to validate a dataframe. Niels kindly provided some code to reproduce the issue, so I built on that here to see how Hamilton would fare. 

## Code to Reproduce
```python
import time
import random
import pandas as pd
import pandera as pa

from hamilton import driver, ad_hoc_utils, base
from hamilton.experimental import h_ray
from hamilton.function_modifiers import extract_columns, check_output

NUM_COLS = 100_000
cols = [f'i_{col}' for col in range(NUM_COLS)]

series_schema = pa.SeriesSchema(int, pa.Check.isin([0, 1, 2, 3]))


@check_output(schema=series_schema)
@extract_columns(*cols)
def data(number_of_columns: int) -> pd.DataFrame:
    df = pd.DataFrame.from_records([
        {
            f'i_{col}': random.choice([0, 1, 2, 3])
            for col in range(number_of_columns)
        }
        for _ in range(10)
    ])
    return df

if __name__ == '__main__':
    temp_module = ad_hoc_utils.create_temporary_module(data)
    start = time.time()
    print('Creating DAG')
    dr = driver.Driver({'number_of_columns': NUM_COLS}, temp_module)
    print(f"Created DAG in: {(time.time() - start)} seconds")
    df = dr.execute(cols)
    # dr.visualize_execution(cols, './viz.dot', {})
    # schema(data, lazy=True)
    print(f"Total Hamilton time: {(time.time() - start)} seconds")
    # print(df.head())

    del df
    del dr

    import ray
    ray.init()
    start = time.time()
    print('Creating RAY DAG')
    rga = h_ray.RayGraphAdapter(result_builder=base.SimplePythonDataFrameGraphAdapter())
    dr = driver.Driver({'number_of_columns': NUM_COLS}, temp_module, adapter=rga)
    print(f"Created RAY DAG in: {(time.time() - start)} seconds")
    df = dr.execute(cols)
    # dr.visualize_execution(cols, './viz.dot', {})
    # schema(data, lazy=True)
    print(f"Total RAY Hamilton time: {(time.time() - start)} seconds")
    print(df.head())
    ray.shutdown()
```
Output:
```
Creating DAG
Created DAG in: 1117.1986498832703 seconds
Total Hamilton time: 1570.403818845749 seconds
Creating RAY DAG
Created RAY DAG in: 30479.727458000183 seconds
...
```

## Library & System Information
I ran this on my mac laptop.

# Expected behavior
We shouldn't take that long. 

# Additional context
This isn't likely a priority - but planting a way to reproduce an issue where object creation takes a while.

**Comment by skrawcz** [comment]
With #169 -- I see:
```
Creating DAG
Created DAG in: 6.1067540645599365 seconds
Total Hamilton time: 66.15090799331665 seconds
```
!

**Comment by skrawcz** [comment]
Vanilla Hamilton is fixed.

Now need to figure out Ray and Dask.

**Comment by elijahbenizzy** [comment]
Yep, we should dig in to why they're that much slower... Can take a look later this weekend possibly.

**Comment by skrawcz** [comment]
Closing this issue for now -- punting on Ray & Dask until it crops up again.
