### ISSUE TITLE
Enhancement: Add capability to use a DataFrame as a template for the target output.

### ISSUE THREAD

**Issue by straun** [stitchfix/hamilton#19]
Currently if the caller has a DataFrame structure that they are targeting then they need to ensure they match the names of the columns correctly and manually convert the Series types. If the `output_columns` or other parameter of the `execute` function took a DataFrame as a template then the output columns would match the data columns and each series can be delivered using `astype` conversion.

You will probably need something like a `DictionaryError` for the scenario where there is a column in the DataFrame template that is not in the data columns available.

There is also the option to be able to process compound column names from the DataFrame to map into a more structured DataFrame. This would involve having a join character e.g. `_`.

**Comment by skrawcz** [comment]
Going to close this issue for now. Hamilton now support more than creating dataframes, so supporting this feature probably doesn't make sense for now.
