### ISSUE TITLE
Better notebook support for visualizing DAGs

### ISSUE THREAD

**Issue by skrawcz** [stitchfix/hamilton#205]
**Is your feature request related to a problem? Please describe.**
If you are using Hamilton in a jupyter notebook, we should enable creating a visualization easily when you request a DAG visualized.

**Describe the solution you'd like**
In simplest terms, doing something like `dask` does for visualizing its DAGs in a notebook would be sweet.

Requirements:

1. Able to display in a notebook.
2. Able to handle really large graphs -- or some way to help people wrangle them to display.

e.g. 
```python
dr = driver.Driver(...)
dr.visualize_execution(...)
# this creates an image that is displayed
```
**Thought** - the solution here might be as simple as returning the graphviz object...

Perhaps having a default print out of a driver object could also be useful?
```python
dr = driver.Driver(...)
dr
# this prints out some information about the DAG created -- perhaps even a rough visualization, much like dask does?
```

**Describe alternatives you've considered**
You save the image, and then load it -- I don't believe this will be the best experience though:
```python
from IPython.display import Image
...
dr.visualize_execution(..., 'my_dag.png', ...)
...
Image('my_dag.png')
# this would then display
```

**Additional context**
For ideas/inspiration: 

* https://docs.dask.org/en/stable/graphviz.html?highlight=visualize
* [Graphviz docs](https://h1ros.github.io/posts/introduction-to-graphviz-in-jupyter-notebook/)

**Comment by elijahbenizzy** [comment]
On my phone but I've prototyped some examples 

Non-interactive 
![image](https://user-images.githubusercontent.com/3886307/196477931-4df860da-0742-43e2-b05c-988ef7f45c8f.jpeg)

Interactive ![image](https://user-images.githubusercontent.com/3886307/196477985-6c50601e-d2af-487d-a3d2-9b8a21f6a7c5.jpeg)

These run after the hello world view in the notebook. Planning to add examples.

**Comment by skrawcz** [comment]
Nice -- but is there a way we just return the graphviz/networkx object?

**Comment by elijahbenizzy** [comment]
> Nice -- but is there a way we just return the graphviz/networkx object?

Currently it doesn't but I think we should change it to-- makes the above code much easier to work with.
