### ISSUE TITLE
Create HOW TOs for integration with popular ETL frameworks/methodology

### ISSUE THREAD

**Issue by skrawcz** [stitchfix/hamilton#22]
**Is your feature request related to a problem? Please describe.**
Hamilton has a small footprint. It can be run inside existing ETLs very easily. We should have documentation to reflect
that fact to help users understand how simple it is to get it working.

**Describe the solution you'd like**
We should have examples/documentation to cover:

1. Metaflow
2. Airflow
3. Dagster
4. Flyte
5. Your custom scheduler

**Describe alternatives you've considered**
N/A

**Additional context**
We want people to be able to cut and paste code easily. Also having examples/documentation would help people size what it would look like to get Hamilton into their ETL.

**Comment by elijahbenizzy** [comment]
We are moving repositories! Please see the new version of this issue at https://github.com/DAGWorks-Inc/hamilton/issues/12. Also, please give us a star/update any of your internal links.
