### ISSUE TITLE
Transforms with non-alphanumeric column names (spaces in column names)

### ISSUE THREAD

**Issue by mattharrison** [stitchfix/hamilton#224]
Hey there,

I'm curious to try out Hamilton on a multi-step pandas transform. I'm stuck though because the input CSV has spaces in the column names and I can't find any documentation for dealing with that. I figured there might be a decorator that helps with this but I can't see one.

For example, my input column is named "Lot Frontage" and I want the output to be named "lot_frontage".

**Comment by skrawcz** [comment]
@mattharrison thanks for the issue.

Yeah so we generally recommend people to "normalize" things after ingestion. We require all "columns" to be valid python variable names.

E.g. write a function like:
```python
def _sanitize_columns(df_columns: List[str]) -> List[str]:
    """Renames columns to be valid hamilton names -- and lower cases them.
    :param df_columns: the current column names.
    :return: sanitize column names that work with Hamilton
    """
    return [c.strip().replace("/", "_per_").replace(" ", "_").lower() for c in df_columns]
```
Which can be found in the data quality example [here](https://github.com/stitchfix/hamilton/blob/main/examples/data_quality/pandera/data_loaders.py#L44-L50).

and use it in a loader function such as:
```python
@extract_columns(*data_columns)
def raw_data__base(location: str) -> pd.DataFrame:
    """Extracts the raw data, renames the columns to be valid python variable names, and assigns an index.
    :param location: the location to load from
    :return:
    """
    df = pd.read_csv(location, sep=";")
    # rename columns to be valid hamilton names -- and lower case it
    df.columns = _sanitize_columns(df.columns)
    # create proper index -- ID-Month-Day;
    index = (
        df["id"].astype(np.str)
        + "-"
        + df["month_of_absence"].astype(np.str)
        + "-"
        + df["day_of_the_week"].astype(np.str)
    )
    df.index = index
    return df
```
Which can be found in the data quality example [here](https://github.com/stitchfix/hamilton/blob/main/examples/data_quality/pandera/data_loaders.py#L55-L72).

That said -- that's what we recommend. However, if we need to build a "contrib" package that houses utilities like these, let us know that it would be helpful.

**Comment by skrawcz** [comment]
Otherwise we also have a slack group that you can ask questions in as well - https://join.slack.com/t/hamilton-opensource/shared_invite/zt-1bjs72asx-wcUTgH7q7QX1igiQ5bbdcg

**Comment by elijahbenizzy** [comment]
Also welcome from linkedin!

**Comment by elijahbenizzy** [comment]
To add flavor -- we had talked about adding a renaming capability to `extract_columns` (E.G. so it knew the difference that the column `Frontage Lot` meant `frontage_lot`). but haven't found a good motivation yet. The idea is that we're expressing a transformation on top of raw data -- column names, etc... could all change, so encapsulating that logic in a function allows for easy unit testing/abstraction. That said, happy to revisit if you think its high value! Looking for OS input/contributions :)

**Comment by skrawcz** [comment]
@mattharrison any further questions? I was thinking that we could update the documentation to make this clearer -- did you browse any of that? Just trying to figure out where it would be best to mention this.

**Comment by skrawcz** [comment]
@mattharrison closing this issue since I haven't heard back from you. Please reopen if needed.
