### ISSUE TITLE
dbt Hamilton Example

### ISSUE THREAD

**Issue by datarshreya** [stitchfix/hamilton#240]
Notes on the dbt Hamilton example found at [hamilton/examples/dbt](https://github.com/stitchfix/hamilton/tree/main/examples/dbt):

I ran this with
```
dbt-core==1.3.1
dbt-duckdb==1.3.2
dbt-python==0.1
scikit-learn==1.1.3
sf-hamilton==1.11.0
pandera==0.13.4
```

1. `requirements.txt` states `dbt` as a requirement. As of v1.0.0, `pip install dbt` is no longer supported. `dbt-core` would have to be specified instead. Is there a specific version of dbt this should/can be run with? It could be helpful to specify versions in the requirements file.

2. There is an extra space while specifying the `-r` option in the pip install command. Should be `pip install -r requirements.txt` instead of `pip install - r requirements.txt`

3. `dbt run` is throwing an error due to a missing `pandera` requirement, which can be added to the requirements file. The run was successful after `pip install pandera`. **_Before_** the `dbt-fal` commit, `sqlalchemy` was also a missing requirement and had to be added.

Happy to do a PR to make these changes! This is also my first open source Github issue, any feedback is welcome!

**Comment by skrawcz** [comment]
@datarshreya happy for the PR if you want to, else I'll triage and confirm your fix :)

**Comment by datarshreya** [comment]
Will work on the PR!

**Comment by skrawcz** [comment]
Verified this fix. Thanks @datarshreya.
