### ISSUE TITLE
Have `graphviz` be an optional dependency?

### ISSUE THREAD

**Issue by ivirshup** [stitchfix/hamilton#26]
**Is your feature request related to a problem? Please describe.**

This library is already nice and light, but I think it could be lighter!

**Describe the solution you'd like**

Could graphviz be an optional dependency? It's only required for one function (`display`), which I don't think is really core to the functionality of the package.

**Describe alternatives you've considered**

Could keep it in. It is fairly light on its own, though it is a compiled dependency.

**Comment by elijahbenizzy** [comment]
Yeah I don't think its necessary -- an easy workaround (although not perfect) would be to check if its installed and if not error out with a helpful error message saying "Hey, please install graphviz if you want to use this feature". Any chance of opening a PR that removes the dependency and adds the error?

**Comment by elijahbenizzy** [comment]
This has been merged and released. Thank you @ivirshup -- you are our first external contributor 🙌 !
