### ISSUE TITLE
Flink support

### ISSUE THREAD

**Issue by skrawcz** [stitchfix/hamilton#271]
**Is your feature request related to a problem? Please describe.**
Can we better integrate Hamilton with Flink?

**Describe the solution you'd like**
We probably need to prototype a bit to see whether this is possible, but making it easier/simpler to use flink would be great.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by elijahbenizzy** [comment]
We are moving repositories! Please see the new version of this issue at https://github.com/DAGWorks-Inc/hamilton/issues/59. Also, please give us a star/update any of your internal links.

Note that everything else (slack community, pypi packages, etc...) will not change at all.
