### ISSUE TITLE
docs clarifying suggestions

### ISSUE THREAD

**Issue by erexer** [stitchfix/hamilton#288]
* the example `my_script.py` should include `import sys`
* add a note that `pip install sf-hamilton[visualization]` needs to be `pip install "sf-hamilton[visualization]"` for zsh
* doesn't work out of the box with python 3.11 (as far as I can tell), so the `setup.py` file might need to be changed

**Comment by skrawcz** [comment]
Thanks for the issue @erexer !

Clarifying questions:

> * the example `my_script.py` should include `import sys`

can you link the file please? I can't seem to locate this.

> * add a note that `pip install sf-hamilton[visualization]` needs to be `pip install "sf-hamilton[visualization]"` for zsh

Noted, thanks!

> * doesn't work out of the box with python 3.11 (as far as I can tell), so the `setup.py` file might need to be changed

Do you have a stack trace? Otherwise we have #216 open if you wanted to add to it.

**Comment by skrawcz** [comment]
@erexer okay closing this -- and moving 3.11 support chat to #216 .
