### ISSUE TITLE
Follow up TODOs on docs rewrite.

### ISSUE THREAD

**Issue by skrawcz** [stitchfix/hamilton#295]
follow up:
 - [ ] add icon logo
 - [x] #308

To go live:
 - [x] merge docs branch -- docs now live under `/docs/`
 - [ ] #318
 - [ ] ask for feedback
 - [ ] switch links
 - [ ] create redirect

_Originally posted by @skrawcz in https://github.com/stitchfix/hamilton/issues/270#issuecomment-1409555803_

**Comment by CharityKithaka** [comment]
Hey @skrawcz I can help with the remaining tasks.

**Comment by skrawcz** [comment]
Thanks for the offer of help @CharityKithaka! What's your familiarity with [reST](https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html)?

**Comment by CharityKithaka** [comment]
I have read through the documentation and I have worked with a couple of concepts and syntax @skrawcz

**Comment by skrawcz** [comment]
> I have read through the documentation and I have worked with a couple of concepts and syntax @skrawcz

Great! @CharityKithaka how about I give you https://github.com/stitchfix/hamilton/issues/308 as a first task here?

**Comment by CharityKithaka** [comment]
Sure thats great. Thank you @skrawcz

**Comment by elijahbenizzy** [comment]
We are moving repositories! Please see the new version of this issue at https://github.com/DAGWorks-Inc/hamilton/issues/66. Also, please give us a star/update any of your internal links.

Note that everything else (slack community, pypi packages, etc...) will not change at all.
