### ISSUE TITLE
Restructure docs like https://diataxis.fr/ suggests.

### ISSUE THREAD

**Issue by skrawcz** [stitchfix/hamilton#297]
# What
The structure of our docs could be better thought out. https://diataxis.fr/ is a good model - we should emulate what it prescribes.

# Why
Good docs are the foundation of any open source project. Having a clear structure and thus content that maps appropriately will help with that.

# Task
What needs to be done:

1. Assess current content.
2. Design where it should live.
3. Move everything as needed.

**Comment by elijahbenizzy** [comment]
We are moving repositories! Please see the new version of this issue at https://github.com/DAGWorks-Inc/hamilton/issues/67. Also, please give us a star/update any of your internal links.

Note that everything else (slack community, pypi packages, etc...) will not change at all.
