### ISSUE TITLE
how to not hardcode links

### ISSUE THREAD

**Issue by skrawcz** [stitchfix/hamilton#308]
# Context:
With the docs rewrite (https://github.com/stitchfix/hamilton/pull/270#issuecomment-1409555803) -- we ported links over in a hardcoded manner. We should use the linking functionality available to reST instead.

# Task:
Remove hardcoded links and instead use the prescribed reST way.

**Comment by skrawcz** [comment]
@CharityKithaka are you okay with me assigning you this task?

**Comment by CharityKithaka** [comment]
Yes I am.

**Comment by skrawcz** [comment]
> Hey, @skrawcz . I had a question. I am writing about how they can not hardcode links in the docs folder or am also replacing the hardcoded links in the reST docs folder in the project. Or am doing both?

Answering here for context as well. The latter, so replacing hardcoded links in the reST docs folder would be the task please :)

**Comment by CharityKithaka** [comment]
Hey, @skrawcz committed a PR.

**Comment by CharityKithaka** [comment]
Hey @skrawcz would like to take up another task.

**Comment by skrawcz** [comment]
Thanks @CharityKithaka -- thanks for touching them up -- just a few things to address. 

Happy to give you another one after this one is done; but otherwise I currently have you doing https://github.com/stitchfix/hamilton/issues/274 too.

**Comment by CharityKithaka** [comment]
That's okay thank you. 👍
