### ISSUE TITLE
Support Generics

### ISSUE THREAD

**Issue by elijahbenizzy** [stitchfix/hamilton#39]
**Is your feature request related to a problem? Please describe.**
Return/input types of `Tuple[str, str]`, for example, don't work.

**Describe the solution you'd like**
We should have sophisticated subclass checking.

**Describe alternatives you've considered**
Adding an option to bypass compile-time type checking (🤮 )

**Additional context**
Creating metaflow examples and they'd be a lot more self-documenting this way.

**Comment by skrawcz** [comment]
I'm going to close this issue. 1.5.0 will have pretty decent support. It might miss an edge case or two, but we'll fix/assess support on a case by case basis going forward.
