### ISSUE TITLE
Add the ability to mark/tag nodes

### ISSUE THREAD

**Issue by elijahbenizzy** [stitchfix/hamilton#4]
Think @pytest.mark.parametrized -- a way to attach metadata to a set of nodes. 

Use-case -- the FED team wants to be able to mark nodes/data products.

Example:

```python
@tag('actuals')
def my_actuals_column(...) -> pd.Series:
    pass

@tag('actuals', 'full_product')
def column_for_both_actuals_and_full_product() -> pd.Series:
    pass


def intermediate_column() -> pd.Series:
    pass
```

Then `list_available_variables` would also allow us to have these tags in the `Variable` object.

```
driver = Driver(...)
vars = [var for var in driver.list_available_variables() if 'actuals' in var.tags]
```
This would then allow users to build decorators on top of this:

```
@actual_column
# The same as
@tag('actuals')
```

**Comment by elijahbenizzy** [comment]
Going to take a quick stab. First collecting some use-cases:

1. Just running certain nodes (could be done with config.when(), but this is more on the execution side -- E.G. as a filter)
2. Handling Data lineage (see #42)
3. Marking nodes as being part of a data product and filtering for just that
4. Having nodes with specific debugging information (E.G. #41)

Issues that I foresee:

## How to deal with node expanders

Proposal -- tags associate to only the last node in a subdag created by a node decorator. Meaning the artifacts created. Furthermore, tags must be the same for all nodes created by a function.

## How to expose to the users

Let's do it above, with the `Variable` API. It's a nice abstraction over nodes.

## How to define a common set of tags so you're not just memorizing strings

Want to punt on this and say _good software engineering practices will help_. But also, we may want to have a set of reserved tags for internal use...

## Config items as tags

Yeah this is too complicated and don't see a use-case.

**Comment by skrawcz** [comment]
Closing this old issue - see #83 .
