### ISSUE TITLE
Prototype Data Quality Feature

### ISSUE THREAD

**Issue by skrawcz** [stitchfix/hamilton#41]
**Is your feature request related to a problem? Please describe.**
When creating pipelines, data issues can silently wreak havoc; your code didn't change but the data did and now things are wonky...

To combat that, there are projects like [pandera](https://pandera.readthedocs.io/en/stable/) that allow you to annotate functions with expectations, and at runtime, have those expectations checked and appropriately exposed.

Hamilton, should have some support for runtime data quality checks, so that we can not only support clean code bases, but also clean data as well.

**Describe the solution you'd like**
We should prototype an approach where there is:

1. A way to set expectations on the output of a function, what the data should like.
2. Use those expectations either right after function execution, or on conclusion of a Hamilton DAG, or some other way.
3. A way to specify what should happen when an expectation is not met -- e.g. log warnings, surface warnings, or stop execution.
4. Thinking of a way to bootstrap these expectations from a dataset -- so that users can update/change expectations easily as time goes on.

Directionally https://pandera.readthedocs.io/en/stable/ seems like a good first approach to try, i.e. via decorators. 

**Describe alternatives you've considered**
This is something that as the prototype is being built out, we're thinking about alternatives considered too.

**Additional context**
Some ideas on approaches:
- https://pandera.readthedocs.io/en/stable/
- https://github.com/awslabs/deequ
- https://greatexpectations.io/

**Comment by skrawcz** [comment]
One idea for implementation -- decorate functions with something that will inspect the output.

```python
@check_output({'type': float, 'range': (0.0, 10000.0)})
def SOME_IMPORTANT_OUTPUT(input1: pd.Series, input2: pd.Series) -> pd.Series:
   """Does some complex logic"""
```

**Comment by elijahbenizzy** [comment]
Some thoughts about implementation:
1. When/how do we want checks to fail? This could be configurable -- should that be at the local or global level?
2. We could make this an additional output node -- E.G. for every node outputted by that function, we add a check on it... We have the decorator abstraction to make this really easy.
3. This could be (a) a runtime error or (b) an output in the DAG itself. We'd want some way of knowing which nodes are outputs to the DAG, see [tags](https://github.com/stitchfix/hamilton/issues/4) for something that could help mark them correctly. If this is a runtime error, then we need to figure out what the node is like (kind of a side-effect?).

I think we should first prototype this as a decorator that appends a pass-through node that runs the check, or just runs the check on its own. Then we can think about running more configurations of different failure modes. But putting the fatality of it in the decorator itself might make a lot of sense. Allowing for thresholds, etc... might be nice as well.

```python
@check_output({'type': float, 'range': (0.0, 10000.0), 'max_empty': 0.0, }, fatal=True)
def SOME_IMPORTANT_OUTPUT(input1: pd.Series, input2: pd.Series) -> pd.Series:
   """Does some complex logic"""
```

**Comment by skrawcz** [comment]
H/T @jimdowling 
> [Jim Dowling](https://app.slack.com/team/U027V74KCJC)  [23 minutes ago](https://featurestoreorg.slack.com/archives/C027R95A8UA/p1645599525481199?thread_ts=1645569514.060789&cid=C027R95A8UA)
> For me, data validation can be group into data validation rules that apply at the row level or dataframe level. Assuming we have a pipeline that is computing a dataframe that we want to write somewhere. Then the pipeline will run periodically and you also need to be able to do something about a failed rule - exclude a row, log a row for debugging, fail the write of the whole dataframe, etc.
> Then there is data monitoring, which is a whole different problem - like feature monitoring.
> 
> [Stefan Krawczyk](https://app.slack.com/team/U029N92L9UL)  [4 minutes ago](https://featurestoreorg.slack.com/archives/C027R95A8UA/p1645600712260809?thread_ts=1645569514.060789&cid=C027R95A8UA)
> oh yep.
> I think excluding/omitting rows would be a little tough — that would be better modeled as a separate transform step. Otherwise logging a warning, or halting execution would be quite do-able and configurable I’m thinking.
> 
> [Stefan Krawczyk](https://app.slack.com/team/U029N92L9UL)  [2 minutes ago](https://featurestoreorg.slack.com/archives/C027R95A8UA/p1645600806612369?thread_ts=1645569514.060789&cid=C027R95A8UA)
> To me data monitoring is just a bit of a layer on top, where it’s auto-adjusting these “rules” — and likely out of scope of Hamilton itself — because Hamilton doesn’t control materialization and wouldn’t know about previous runs by itself.
> 
> [Jim Dowling](https://app.slack.com/team/U027V74KCJC)  [1 minute ago](https://featurestoreorg.slack.com/archives/C027R95A8UA/p1645600851553179?thread_ts=1645569514.060789&cid=C027R95A8UA)
> Agreed on both points

**Comment by elijahbenizzy** [comment]
Rough sketch of data quality. Going to implement it as a prototype then send it to a few folks for feedback who've expressed interest. Will tag and hopefully start a discussion!

**Comment by skrawcz** [comment]
One thought: handling dataframe/dict of output. Do we specify things on a per column/field basis (at the top level, or within each kwarg)? Or some other way? or both?

**Comment by elijahbenizzy** [comment]
> One thought: handling dataframe/dict of output. Do we specify things on a per column/field basis (at the top level, or within each kwarg)? Or some other way? or both?

Yeah I just had that same though. I've designed for series, but we should have something for dataframes/dicts. You could imagine something like:

```python
@check_output(column="col_1", max_val=10)
@check_output(column="col_2", max_val=20)
def important_df_function() -> pd.DataFrame:
    ...
```

Or:

```python
@check_output(col_1={'max_val' : 20}, col_1={'max_val' : 20})
def important_df_function() -> pd.DataFrame:
    ...
```
With the decorator framework the second is easier but its a little uglier IMO.

**Comment by skrawcz** [comment]
hmm - riffing some more ideas here:

Same as above but using `dict()`:
```python
@check_output(col_1=dict(max_val=20), col_2=dict(max_val=20))
def important_df_function() -> pd.DataFrame:
    ...
```

or 

Splitting each kwarg by column:
```python
@check_output(max_val={"col_1": 20, "col_2": 20})
def important_df_function() -> pd.DataFrame:
    ...
```

I personally like this option the most from a visual esthetics perspective (would change "column" to perhaps "name"):
```python
@check_output(column="col_1", max_val=10)
@check_output(column="col_2", max_val=20)
def important_df_function() -> pd.DataFrame:
    ...
```

But perhaps this is where we maybe do something like Pandera and one would define some object and instead do:

```python
schema=... # some object type? or a dict of column to dicts? or?

@check_output(schema=schema)
def important_df_function() -> pd.DataFrame:
    ...

```

**Comment by skrawcz** [comment]
@chrisaddy would love for you to branch off of #115 and see what approach would work best for dataframes:

# Option 1 - individual checkout outputs for each column 
```python
@check_output(name="col_1", max_val=10)
@check_output(name="col_2", max_val=20)
def important_df_function() -> pd.DataFrame:
```

# Option 2 - come up with a Hamilton schema was analogous to Pandera, like in your example -- https://github.com/stitchfix/hamilton/issues/123
```python
schema=... # some object type? or a dict of column to dicts? or?

@check_output(schema=schema)
def important_df_function() -> pd.DataFrame:
```

# Option 3 - integrate pandera as a custom validator -- like in your example https://github.com/stitchfix/hamilton/issues/123
