### ISSUE TITLE
Prototype Compile Hamilton on to an Orchestration Framework

### ISSUE THREAD

**Issue by skrawcz** [stitchfix/hamilton#44]
**Is your feature request related to a problem? Please describe.**
Another way to scale a Hamilton DAG is to break it up into stages and have some other orchestrator handle execution. Hamilton need not implement these functions itself -- it could just compile and delegate execution to these frameworks.

E.g. I have a Hamilton DAG, but I want to use my in house Metaflow system -- the user should be able to generate code to run on Metaflow.

**Describe the solution you'd like**
A prototype to show how you could go from a Hamilton DAG to a DAG/Pipeline of some orchestration framework.

E.g.:
* [Metaflow](https://metaflow.org/)
* [Kubeflow](https://www.kubeflow.org/docs/components/pipelines/sdk/python-function-components/)
* [Dagster](https://dagster.io/)
* [Prefect](https://www.prefect.io/)
* [Airflow](https://airflow.apache.org/)
* etc

You'd have to think through the flow to do this:
e.g. define Hamilton DAG -> Compile to X Framework -> Commit code -> Run code on Framework X

We should prototype at least two implementations and see how we'd need to structure the code to make it manageable to maintain.

**Describe alternatives you've considered**
Hamilton could implement something like these other orchestration frameworks do, but that seems like a heavy lift. Better to try compiling to an existing framework.

**Additional context**
N/A

**Comment by elijahbenizzy** [comment]
We are moving repositories! Please see the new version of this issue at https://github.com/DAGWorks-Inc/hamilton/issues/16. Also, please give us a star/update any of your internal links.
