### ISSUE TITLE
Improve Documentation

### ISSUE THREAD

**Issue by elijahbenizzy** [stitchfix/hamilton#51]
**Is your feature request related to a problem? Please describe.**
Docs are good for what we have now but will make it tougher to onboard users. We need a stronger narrative/prettier format.

**Describe the solution you'd like**
@elijahbenizzy has started this on gitbook -- this is a WIP. hamilton-docs.gitbook.io.

**Describe alternatives you've considered**
Beefing up READMEs, using another platform.

**Additional context**
Looking good so far! Really excited about feedback on docs, and potentially getting contributors. If you want to contribute post here and I can figure out adding you to the gitbook org. For now we have a free "community plan" meant for OS.

**Comment by chrisaddy** [comment]
I'd love to help beef up docs, is there a guide to how y'all do docs, style guide?

**Comment by skrawcz** [comment]
> I'd love to help beef up docs, is there a guide to how y'all do docs, style guide?

Other than the various markdown files in this repository, we are using gitbook - https://hamilton-docs.gitbook.io/ at this time. Not real style guide there other than what we've setup there.

However, we are looking to switch documentation systems, as gitbook doesn't allow multiple versions -- @jameslamb suggested using readthedocs instead in https://github.com/stitchfix/hamilton/issues/69, as it allows for docs to match to release versions.

@chrisaddy do you have any experience setting up a documentation system from scratch?

**Comment by skrawcz** [comment]
https://readthedocs.org/ could be a good candidate since it allows multiple versions.

**Comment by jameslamb** [comment]
Yep, I still support that! And I have set it up for projects before, would be happy to help yall if you want to try it.

**Comment by elijahbenizzy** [comment]
Related is https://github.com/stitchfix/hamilton/issues/69 -- we put it on gitbook, but I think better syncing would be 🔥 and we're a little behind other OS projects. Would love insights!

**Comment by skrawcz** [comment]
Closing this in favor of #295 and #297 given that #270 just merged.
