### ISSUE TITLE
Revamp methods of parametrizing the DAG

### ISSUE THREAD

**Issue by elijahbenizzy** [stitchfix/hamilton#52]
**Is your feature request related to a problem? Please describe.**

Currently, we have two ways to pass data into/parametrize the DAG:

1. By passing in a `config` -- this takes the form of a constructor argument to the `function_graph` during instantiation. Note that this is both used as input data to the DAG (on exectution) as well as a configuration for constructing the DAG
2. By passing in `overrides` -- these are intended to override node values that already exist.

The problem is that this does not allow users to build a DAG once and execute it multiple times with different configurations. However, the `function_graph` actually *allows* for this using `execute_static`, but the parameters to function graph replace it with the `config` (https://github.com/stitchfix/hamilton/blob/cb5a11c04bdcdc62874745f77292284d4cdf982f/hamilton/graph.py#L282) 

**Describe the solution you'd like**
We should separate this into three different notions:
1. `config` -- allows for pre-configuration of the DAG. Used primarily to determine DAG shape, but also passed in as inputs.
2. `inputs` -- passes data into a run of the DAG (effectively filling the purpose of a user-defined-node)
3. `overrides` -- overrides nodes in the DAG

`inputs` will become the union of `config` and `inputs`, for two reasons:

1. To maintain backwards compatibility 
2. To reduce cognitive burden when calling the DAG for inputs that are required both in instantiation and execution

This will just require a change to the default driver. TBD what we do for inputs/configs clashing.

**Describe alternatives you've considered**
We could forego `overrides` entirely -- allowing `inputs` to override the DAG. Personally I think this is an easy way to shoot oneself in the foot, but it does simplify the API.

**Additional context**
Writing the docs and realizing the original design is not great.

**Comment by skrawcz** [comment]
This could help with #43 .


> TBD what we do for inputs/configs clashing.
IMO, to be clearer that `config` is used as `inputs` I think it should be called something more descriptive depending on the behavior of how inputs modifies things.

I think there are two options to maintain backwards compatibility:

## option 1 -- things passed into the constructor, are "default" values used at execution time.

The logic in execute would be something like:
```
Log overlap in default inputs and inputs passed into execute.
For the required inputs to execute the graph:
 - fill with defaults
 - override with inputs
 - error if incomplete inputs found.
```

Thus the split would be:

`config_and_default_inputs`
`inputs`
`overrides`

## option 2 -- things passed into the constructor are inputs that are invariant to execute

The logic in execute would thus be something like:

```
Ensure inputs & invariant values do not overlap -- error otherwise
For the required inputs to execute the graph:
 - fill from invariant values
 - take from inputs
 - error if incomplete inputs found.
```

Thus the split would be:
`config_and_invariant_inputs`
`inputs`
`overrides`

**Comment by elijahbenizzy** [comment]
Added to 1.3.0 milestone, will be releasing soon
