### ISSUE TITLE
Verify `extract_columns` support for distributed dataframes

### ISSUE THREAD

**Issue by elijahbenizzy** [stitchfix/hamilton#54]
**Is your feature request related to a problem? Please describe.**
This is only supported for pandas.

**Describe the solution you'd like**
TBD, but it should *just work*. Some options:

1. We have `extract_columns` be a class that's subclassable for each type and they add it in as a plugin. `extract_columns` then knows the mapping from DF type (from the function signature) to implementation
2. The executor passes in the types for this
3. We have some sort of transform-writing-friendly dataframe representation (although this is tricky for many reasons.)
4. Additional decorators for dask, spark, etc...

**Additional context**

**Comment by skrawcz** [comment]
I have tested this locally for:

- [x]  dask
- [x]  ray

and they worked just fine.

TODO: 
- [ ]  spark

**Comment by skrawcz** [comment]
To test I did something like:

```python

def spend_1(spend_location: str) -> ps.Series:
    """Dummy function showing how to wire through loading data.

    :param spend_location:
    :return:
    """
    return ps.from_pandas(pd.Series([10, 10, 20, 40, 40, 50], name='spend'))


def signups_1(signups_location: str) -> ps.Series:
    """Dummy function showing how to wire through loading data.

    :param signups_location:
    :return:
    """
    return ps.from_pandas(pd.Series([1, 10, 50, 100, 200, 400], name='signups'))


from hamilton import function_modifiers

@function_modifiers.extract_columns(*['spend', 'signups'])
def dataframe_return(spend_1: ps.Series, signups_1: ps.Series) -> pd.DataFrame:
    df = ps.DataFrame(spend_1)
    df['signups'] = signups_1
    return df


```

For each of them -- this one was for spark, and it didn't complain :)
