### ISSUE TITLE
1.3.0 release

### ISSUE THREAD

**Issue by elijahbenizzy** [stitchfix/hamilton#59]
Tracking here. Goal to do this tomorrow. Order of business is:
- [x] Delete `augment` from `decorator-refactor` 
- [x] Merge `distributed_prototype` (@skrawcz)  (https://github.com/stitchfix/hamilton/pull/47)
- [x] Rebase, merge `decorator-refactor` (@elijahbenizzy) (https://github.com/stitchfix/hamilton/pull/28) 
- [x] Rebase, merge `fix-inputs` (https://github.com/stitchfix/hamilton/pull/56)
- [x] Rebase, merge `stefan/refactor_visualization` (@skrawcz) (https://github.com/stitchfix/hamilton/pull/58)
- [x] Create a candidate release
- [x] Run some tests in internal tooling
- [ ] Add any documentation required (`@stefan`)
- [x] Announce on discord
- [x] Add 1.3.0 commit
- [x] Publish library

**Comment by skrawcz** [comment]
Just need to work on documentation now!
