### ISSUE TITLE
Do we want to support iterators for data loading?

### ISSUE THREAD

**Issue by skrawcz** [stitchfix/hamilton#68]
# What?
If we want to chunk over data, a natural way to do that is via an iterator.

## Example: Enable "input" functions to be iterators
```python
def my_loading_funct(...) -> Iterator[pd.Series]:
     ...
     yield some_chunk 
```
This is fraught with some edge cases. But could be a more natural way to chunk over large data sets? This perhaps requires a new driver -- as we'd want some `next()` type semantic logic on the output of execute...

_Originally posted by @skrawcz in https://github.com/stitchfix/hamilton/issues/43#issuecomment-1030961335_

## Things to think through whether this is something useful to have:

1. Where would we allow this? Only on "input" nodes?
2. How would we exercise them in a deterministic fashion? i.e. does execute() care? and we iterate over them until they're exhausted? Or does `execute()` only do one iteration?
3. How do we coordinate multiple inputs that are iterators? What if they're of different lengths?
4. How would we ensure people don't create a mess that's hard to debug?
5. Would this work for the distributed graph adapters?

**Comment by elijahbenizzy** [comment]
Yeah I'd need to see more of a workflow/motivating example for this TBH. E.G. a graphadapter that chunks up data and iterates in a streaming sense could be high-value as well...

**Comment by elijahbenizzy** [comment]
We are moving repositories! Please see the new version of this issue at https://github.com/DAGWorks-Inc/hamilton/issues/19. Also, please give us a star/update any of your internal links.
