### ISSUE TITLE
Redo documentation setup

### ISSUE THREAD

**Issue by elijahbenizzy** [stitchfix/hamilton#69]
**Is your feature request related to a problem? Please describe.**
~Currently, gitbooks syncs with a specific `documentation` branch. This does not guarentee that it syncs with releases though.~

**Describe the solution you'd like**
~If gitbooks.io doesn't allow for this, let's look at a statically hosted page using github pages or some other hosting service. Ideally we'd even be able to version it with the release version so you can see old docs.~

----- 
We should consider read the docs for hosting -- since it seems to be the default for python projects of scale.

Tasks:

- [x] Scope what's required to set read the docs up. 
- [x] Determine how it would function and be rebuilt.
- [ ] #297
- [x] Plan migration from gitbooks.

Some examples of docs to emulate:

* https://insitro.github.io/redun/
* https://pandera.readthedocs.io/
* They all seem to use https://github.com/pradyunsg/furo

**Comment by jameslamb** [comment]
Ah, a `documentation` branch! I was wondering where the docs at https://hamilton-docs.gitbook.io/docs/ came from.

> Ideally we'd even be able to version it with the release version so you can see old docs.

In LightGBM, we've had a great experience for 4+ years with the readthedocs service. It allows for building different versions of your docs from source control based on git tags.

https://github.com/microsoft/LightGBM/issues/4236#issuecomment-829627328

https://lightgbm.readthedocs.io/en/latest/

<img width="1421" alt="Screen Shot 2022-03-27 at 4 04 29 PM" src="https://user-images.githubusercontent.com/7608904/160300960-c53c3861-cbdd-4fa4-b3f6-0cbaf0fdbf73.png">

**Comment by elijahbenizzy** [comment]
@jameslamb would love to learn from your experience with lightgbm -- that's a very sleek look. Where's a good place to start?

**Comment by jameslamb** [comment]
@elijahbenizzy sure! I also just set up readthedocs ("RTD") on one of my little side projects, so I have recent experience doing this. Would be happy to get on a call with you and @skrawcz some time and pair if you'd like.

Here's a high-level overview:

1. go to https://readthedocs.org/accounts/login/ and log in with your GitHub
2. click "import a project", and import `hamilton`
    - that'll reserve `hamilton.readthedocs.io`, and default to building from the `main` branch on every commit to `main` (no more separate `documentation` branch)
3. set up a `.readthedocs.yaml` config file at the root of the repo, telling RTD how to build your docs
    - reference: https://docs.readthedocs.io/en/stable/config-file/v2.html
    - LightGBM example: https://github.com/microsoft/LightGBM/blob/master/.readthedocs.yaml
    - I *think* RTD only supports `sphinx` and `mkdocs`, but not 100% sure about that
4. once that's all set up, you can enable the "allow people to flip between different versions" thing from my screenshot  above by modifying RTD's settings such that it builds from specific tags (which it calls "versions")
    - here's an example from the setting page for `lightgbm.readthedocs.io`
    - <img width="50%" alt="image" src="https://user-images.githubusercontent.com/7608904/199386942-25ca7420-45ac-4550-b57d-dac1717058a6.png">

Hope that helps!

**Comment by elijahbenizzy** [comment]
@jameslamb thak you -- this is great! Sorry it just slipped my mind recently -- I think I'll be able to get this started, but I'll reach out once I have something! 🙏

**Comment by frenchfrywpepper** [comment]
Stefan or Elijah - Can you create an account at https://readthedocs.org/ then tell me your username? Then I can invite you to the Hamilton project there.

After that you'll be able to see the webhook and configure it on GitHub following these [Instructions](https://docs.readthedocs.io/en/latest/integrations.html#github)

**Comment by elijahbenizzy** [comment]
> Question: How important are the `description` sections to you? Is it important that they have unique formatting? Let's say they can't be uniquely formatted in rst, would you still want them there, just as regular text?
> 
> How it looks in gitbook...
> 
> <img alt="Screenshot 2023-01-25 at 2 57 02 PM" width="975" src="https://user-images.githubusercontent.com/584894/214676112-da18f3ec-e4bd-472d-acb2-f8cd6e791bf1.png">
> 
> How it looks in read the docs...
> 
> https://hamilton-temp.readthedocs.io/en/readthedocs/index.html

Don't think they're super important. Pretty sure they can either be dropped or included as the first line in the new version. Looking good!

**Comment by skrawcz** [comment]
Closing this in favor of #295 and #297.
