### ISSUE TITLE
Enable automated testing for non-stitch-fix accounts

### ISSUE THREAD

**Issue by elijahbenizzy** [stitchfix/hamilton#77]
**Is your feature request related to a problem? Please describe.**
Currently we use Stitch Fix's internal testing system. Thus, due to security concerns, we are limited to only allowing SFIX employees to run the tests.

**Describe the solution you'd like**
We should use a public license -- the free one has 6k build minutes/month which should be enough.

**Describe alternatives you've considered**
We could switch vendors, but that would be more work.

**Additional context**
Want to make it easier for others to contribute!

**Comment by chrisaddy** [comment]
have you thought about github actions? would keep all of it in one place and wouldn't have to worry about messing with your private circleci

**Comment by skrawcz** [comment]
This should be fixed actually -- I moved this repo over to the free open source circleCI tier.
