### ISSUE TITLE
Show pyspark dataframe support

### ISSUE THREAD

**Issue by skrawcz** [stitchfix/hamilton#84]
**Is your feature request related to a problem? Please describe.**
A common question we get, is does Hamilton support spark dataframes? The answer is yes, but it's not ideal at the moment, and we don't have a vanilla example to point to.

It's not ideal because joins are a bit of a pain -- you need to know the index to join on. In the pandas world, we got away with
this because everything had an index associated with it. In spark, you need to provide it, and know when to provide it.

**Describe the solution you'd like**
(1) Provide a vanilla pyspark example.
(2) Provide a pattern to show how to handle multiple spark data sources. Perhaps implement a graph adapter to do so.

**Describe alternatives you've considered**
N/A

**Comment by elijahbenizzy** [comment]
We are moving repositories! Please see the new version of this issue at https://github.com/DAGWorks-Inc/hamilton/issues/21. Also, please give us a star/update any of your internal links.
