### ISSUE TITLE
Explore Ibis Integration

### ISSUE THREAD

**Issue by elijahbenizzy** [stitchfix/hamilton#88]
**Is your feature request related to a problem? Please describe.**
Ibis could happily replace pandas, and its more flexible (scalable, etc...)

**Describe the solution you'd like**
Ibis dataframes instead of pandas dataframes. Perhaps a plugin framework.

**Comment by skrawcz** [comment]
https://github.com/ibis-project

**Comment by elijahbenizzy** [comment]
Haven't had time but I really like the idea of this -- Ibis is another approach that could allow clean scaling and integrate nicely with graphadapters.

**Comment by elijahbenizzy** [comment]
We are moving repositories! Please see the new version of this issue at https://github.com/DAGWorks-Inc/hamilton/issues/25. Also, please give us a star/update any of your internal links.
